/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "rain_sensor.h"
//#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "rain_sensor.h"
#include "stm32f4xx.h"

void LED_Init(void)
{
    // Enable clock for GPIOD
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;

    // Set PD12 as output
    GPIOD->MODER &= ~(0x3 << (12 * 2)); // Clear bits
    GPIOD->MODER |=  (0x1 << (12 * 2)); // Output mode

    // Push-pull, no pull-up/pull-down
    GPIOD->OTYPER &= ~(1 << 12);
    GPIOD->PUPDR &= ~(0x3 << (12 * 2));
}

void LED_On(void)
{
    GPIOD->ODR |= (1 << 12);
}

void LED_Off(void)
{
    GPIOD->ODR &= ~(1 << 12);
}

void delay_ms(volatile uint32_t ms)
{
    for (volatile uint32_t i = 0; i < ms * 8000; ++i); // Crude delay at 16 MHz
}

int main(void)
{
    RainSensor_Init();
    LED_Init();

    while (1)
    {
        uint8_t digital = RainSensor_ReadDigital();
        uint16_t analog = RainSensor_ReadAnalog();

        // Turn LED ON if rain is detected OR analog wetness < threshold
        if (digital == 1 || analog < 2000)
        {
            LED_On();
        }
        else
        {
            LED_Off();
        }

        delay_ms(500); // Optional delay
    }
}
