/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f4xx.h"

#include <stdint.h>
#include <stdio.h>
#include "rain_sensor.h"
#include "soil_sensor.h"
#include "dht22.h"
#include "uart.h"
#include"lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void int_to_str(uint8_t num, char *buf);



void delay_ms(volatile uint32_t ms)
{
    for (volatile uint32_t i = 0; i < ms * 8000; ++i); // Crude delay at 16 MHz
}

int main(void)
{

uint8_t temperature = 0, humidity = 0;
char buffer[70];
adc_init();

DHT11_Init();
RainSensor_Init();
UART2_Init();
UART2_SendString("DHT11 Test Started...\r\n");
LcdInit();

    while (1)
    {
        uint8_t digital = RainSensor_ReadDigital();
        uint16_t analog = RainSensor_ReadAnalog();

         UART2_SendString("Rain Detected =");
         UART2_SendNumber(digital);
         UART2_SendNumber(analog);
         UART2_SendString("\r\n");
         delay_ms(1000);

        uint16_t moisture = read_soil_moisture();
        UART2_SendString("soil Mositure = ");
        UART2_SendNumber(moisture);
        UART2_SendString("\r\n");
        delay_ms(1000);

        char line1[20], line2[20];
        sprintf(line1, "Temp:%dC Hum:%d%%", temperature, humidity);
        sprintf(line2, "Rain:%d Soil:%d", analog, moisture);

        LcdWriteByte(LCD_CMD, LCD_CLEAR);
        LcdPuts(LCD_LINE1, line1);
        LcdPuts(LCD_LINE2, line2);
        delay_ms(1000);


     /*   if (DHT11_Read(&temperature, &humidity))
                {
                    sprintf(buffer, "Temp: %d°C, Humidity: %d%%\r\n", temperature, humidity);
                }
                else
                {
                    sprintf(buffer, "DHT11 Read Failed\r\n");
                }

                UART2_SendString(buffer);    }*/
        if (DHT11_Read(&temperature, &humidity))
        {
            char line1[17], line2[17];
            sprintf(line1, "Temp: %dC", temperature);
            sprintf(line2, "Hum:  %d%%", humidity);

            LcdWriteByte(LCD_CMD, LCD_CLEAR);   // Clear LCD
            LcdPuts(LCD_LINE1, line1);          // Display temperature
            LcdPuts(LCD_LINE2, line2);          // Display humidity

            sprintf(buffer, "Temp: %dC, Hum: %d%%\r\n", temperature, humidity);
        }
        else
        {
            LcdWriteByte(LCD_CMD, LCD_CLEAR);   // Clear LCD
            LcdPuts(LCD_LINE1, "DHT11 Failed"); // Error message

            sprintf(buffer, "DHT11 Read Failed\r\n");
        }

        UART2_SendString(buffer);  // Send data over UART2

    }
}
